// traits, ideals, bonds, flaws, maleFirstnames, femaleFirstnames,lastnames, characteristics, spells

var traits = [
    "I idolize a particular hero of my faith and constantly refer to that person's deeds and example.",
    "I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.",
    "I see omens in every event and action. The gods try to speak to us, we just need to listen.",
    "Nothing can shake my optimistic attitude.",
    "I quote (or misquote) the sacred texts and proverbs in almost every situation.",
    "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.",
    "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.",
    "I've spent so long in the temple that I have little practical experience dealing with people in the outside world.",
    "I fall in and out of love easily, and am always pursuing someone.",
    "I have a joke for every occasion, especially occasions where humor is inappropriate.",
    "Flattery is my preferred trick for getting what I want.",
    "I'm a born gambler who can't resist taking a risk for a potential payoff.",
    "I lie about almost everything, even when there's no good reason to.",
    "Sarcasm and insults are my weapons of choice.",
    "I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.",
    "I pocket anything I see that might have some value.",
    "I always have plan for what to do when things go wrong.",
    "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.",
    "The first thing I do in a new place is note the locations of everything valuable--or where such things could be hidden.",
    "I would rather make a new friend than a new enemy.",
    "I am incredibly slow to trust. Those who seem the fairest often have the most to hide.",
    "I don't pay attention to the risks in a situation. Never tell me the odds.",
    "The best way to get me to do something is to tell me I can't do it.",
    "I blow up at the slightest insult.",
    "I know a story relevant to almost every situation.",
    "Whenever I come to a new place, I collect local rumors and spread gossip.",
    "I'm a hopeless romantic, always searching for that 'special someone'.",
    "Nobody stays angry at me or around me for long, since I can defuse any amount of tension.",
    "I love a good insult, even one directed at me.",
    "I get bitter if I'm not the center of attention.",
    "I'll settle for nothing less than perfection.",
    "I change my mood or my mind as quickly as I change key in a song.",
    "I judge people by their actions, not their words.",
    "If someone is in trouble, I'm always willing to lend help.",
    "When I set my mind to something, I follow through no matter what gets in my way.",
    "I have a strong sense of fair play and always try to find the most equitable solution to arguments.",
    "I'm confident in my own abilities and do what I can to instill confidence in others.",
    "Thinking is for other people. I prefer action.",
    "I misuse long words in an attempt to sound smarter.",
    "I get bored easily. When am I going to get on with my destiny.",
    "I believe that everything worth doing is worth doing right. I can't help it--I'm a perfectionist.",
    "I'm a snob who looks down on those who can't appreciate fine art.",
    "I always want to know how things work and what makes people tick.",
    "I'm full of witty aphorisms and have a proverb for every occasion.",
    "I'm rude to people who lack my commitment to hard work and fair play.",
    "I like to talk at length about my profession.",
    "I don't part with my money easily and will haggle tirelessly to get the best deal possible.",
    "I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me.",
    "I've been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.",
    "I am utterly serene, even in the face of disaster.",
    "The leader of my community has something wise to say on every topic, and I am eager to share that wisdom.",
    "I feel tremendous empathy for all who suffer.",
    "I'm oblivious to etiquette and social expectations.",
    "I connect everything that happens to me to a grand cosmic plan.",
    "I often get lost in my own thoughts and contemplations, becoming oblivious to my surroundings.",
    "I am working on a grand philosophical theory and love sharing my ideas.",
    "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.",
    "The common folk love me for my kindness and generosity.",
    "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.",
    "I take great pains to always look my best and follow the latest fashions.",
    "I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.",
    "Despite my birth, I do not place myself above other folk. We all have the same blood.",
    "My favor, once lost, is lost forever.",
    "If you do me an injury, I will crush you, ruin your name, and salt your fields.",
    "I'm driven by a wanderlust that led me away from home.",
    "I watch over my friends as if they were a litter of newborn pups.",
    "I once ran twenty-five miles without stopping to warn my clan of an approaching orc horde. I'd do it again if I had to.",
    "I have a lesson for every situation, drawn from observing nature.",
    "I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.",
    "I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.",
    "I feel far more comfortable around animals than people.",
    "I was, in fact, raised by wolves.",
    "I use polysyllabic words to convey the impression of great erudition.",
    "I've read every book in the world's greatest libraries--or like to boast that I have.",
    "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.",
    "There's nothing I like more than a good mystery.",
    "I'm willing to listen to every side of an argument before I make my own judgment.",
    "I...speak...slowly...when talking...to idiots...which...almost...everyone...is...compared...to me.",
    "I am horribly, horribly awkward in social situations.",
    "I'm convinced that people are always trying to steal my secrets.",
    "My friends know they can rely on me, no matter what.",
    "I work hard so that I can play hard when the work is done.",
    "I enjoy sailing into new ports and making new friends over a flagon of ale.",
    "I stretch the truth for the sake of a good story.",
    "To me, a tavern brawl is a nice way to get to know a new city.",
    "I never pass up a friendly wager.",
    "My language is as foul as an otyugh nest.",
    "I like a job well done, especially if I can convince someone else to do it.",
    "I'm always polite and respectful.",
    "I'm haunted by memories of war. I can't get the images of violence out of my mind.",
    "I've lost too many friends, and I'm slow to make new ones.",
    "I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.",
    "I can stare down a hellhound without flinching.",
    "I enjoy being strong and like breaking things.",
    "I have a crude sense of humor.",
    "I face problems head-on. A simple direct solution is the best path to success.",
    "I hide scraps of food and trinkets away in my pockets.",
    "I ask a lot of questions.",
    "I like to squeeze into small places where no one else can get to me.",
    "I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms.",
    "I eat like a pig and have bad manners.",
    "I think anyone who's nice to me is hiding evil intent.",
    "I don't like to bathe.",
    "I bluntly say what other people are hinting or hiding.",
];
var ideals = [
    "Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)",
    "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)",
    "Charity. I always try to help those in need, no matter what the personal cost. (Good)",
    "Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)",
    "Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)",
    "Aspiration. I seek to prove my self worthy of my god's favor by matching my actions against his or her teachings. (Any)",      
    "Independence. I am a free spirit--no one tells me what to do. (Chaotic)",
    "Fairness. I never target people who can't afford to lose a few coins. (Lawful)",
    "Charity. I distribute money I acquire to the people who really need it. (Good)",
    "Creativity. I never run the same con twice. (Chaotic)",
    "Friendship. Material goods come and go. Bonds of friendship last forever. (Good)",
    "Aspiration. I'm determined to make something of myself. (Any)",
    "Honor. I don't steal from others in the trade. (Lawful)",
    "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)",
    "Charity. I steal from the wealthy so that I can help people in need. (Good)",
    "Greed. I will do whatever it takes to become wealthy. (Evil)",
    "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)",
    "Redemption. There's a spark of good in everyone. (Good)",
    "Beauty. When I perform, I make the world better than it was. (Good)",
    "Tradition. The stories, legends, and songs of the past must never be forgotten. (Lawful)",
    "Creativity. The world is in need of new ideas and bold action. (Chaotic)",
    "Greed. I'm only in it for the money and fame. (Evil)",
    "People. I like seeing the smiles on people's faces when I perform. That's all that matters. (Neutral)",
    "Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)",
    "Respect. People deserve to be treated with dignity and respect. (Good)",
    "Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)",
    "Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)",
    "Might. If I become strong, I can take what I want--what I deserve. (Evil)",
    "Sincerity. There's no good pretending to be something I'm not. (Neutral)",
    "Destiny. Nothing and no one can steer me away from my higher calling. (Any)",
    "Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization. (Lawful)",
    "Generosity. My talents were given to me so that I could use them to benefit the world. (Good)",
    "Freedom. Everyone should be free to pursue his or her livelihood. (Chaotic)",
    "Greed. I'm only in it for the money. (Evil)",
    "People. I'm committed to the people I care about, not to ideals. (Neutral)",
    "Aspiration. I work hard to be the best there is at my craft. (Any)",
    "Greater Good. My gifts are meant to be shared with all, not used for my own benefit. (Good)",
    "Logic. Emotions must not cloud our sense of what is right and true, or our logical thinking. (Lawful)",
    "Free Thinking. Inquiry and curiosity are the pillars of progress. (Chaotic)",
    "Power. Solitude and contemplation are paths toward mystical or magical power. (Evil)",
    "Live and Let Live. Meddling in the affairs of others only causes trouble. (Neutral)",
    "Self-Knowledge. If you know yourself, there're nothing left to know. (Any)",
    "Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)",
    "Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)",
    "Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)",
    "Power. If I can attain more power, no one will tell me what to do. (Evil)",
    "Family. Blood runs thicker than water. (Any)",
    "Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)",
    "Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)",
    "Greater Good. It is each person's responsibility to make the most happiness for the whole tribe. (Good)",
    "Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)",
    "Might. The strongest are meant to rule. (Evil)",
    "Nature. The natural world is more important than all the constructs of civilization. (Neutral)",
    "Glory. I must earn glory in battle, for myself and my clan. (Any)",
    "Knowledge. The path to power and self-improvement is through knowledge. (Neutral)",
    "Beauty. What is beautiful points us beyond itself toward what is true. (Good)",
    "Logic. Emotions must not cloud our logical thinking. (Lawful)",
    "No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)",
    "Power. Knowledge is the path to power and domination. (Evil)",
    "Self-improvement. The goal of a life of study is the betterment of oneself.",
    "Respect. The thing that keeps a ship together is mutual respect between captain and crew. (Good)",
    "Fairness. We all do the work, so we all share in the rewards. (Lawful)",
    "Freedom. The sea is freedom--the freedom to go anywhere and do anything. (Chaotic)",
    "Master. I'm a predator, and the other ships on the sea are my prey. (Evil)",
    "People. I'm committed to my crewmates, not to ideals. (Neutral)",
    "Aspiration. Someday I'll own my own ship and chart my own destiny. (Any)",
    "Greater Good. Our lot is to lay down our lives in defense of others. (Good)",
    "Responsibility. I do what I must and obey just authority. (Lawful)",
    "Independence. When people follow orders blindly they embrace a kind of tyranny. (Chaotic)",
    "Might. In life as in war, the stronger force wins. (Evil)",
    "Ideals aren't worth killing for or going to war for. (Neutral)",
    "Nation. My city, nation, or people are all that matter. (Any)",
    "Respect. All people, rich or poor, deserve respect. (Good)",
    "Community. We have to take care of each other, because no one else is going to do it. (Lawful)",
    "Change. The low are lifted up, and the high and mighty are brought down. Change is the nature of things. (Chaotic)",
    "Retribution. The rich need to be shown what life and death are like in the gutters. (Evil)",
    "People. I help people who help me--that's what keeps us alive. (Neutral)",
];

var bonds = [
    "I would die to recover an ancient artifact of my faith that was lost long ago.",
    "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
    "I owe me life to the priest who took me in when my parents died.",
    "Everything I do is for the common people.",
    "I will do anything to protect the temple where I served.",
    "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.",
    "I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.",
    "I owe everything to my mentor--a horrible person who's probably rotting in jail somewhere.",
    "Somewhere out there I have a child who doesn't know me. I'm making the world better for him or her.",
    "I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.",
    "A powerful person killed someone I love. Some day soon, I'll have my revenge.",
    "I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.",
    "I'm trying to pay off an old debt I owe to a generous benefactor.",
    "My ill-gotten gains go to support my family.",
    "Something important was taken from me, and I aim to steal it back.",
    "I will become the greatest thief that ever lived.",
    "I'm guilty of a terrible crime. I hope I can redeem myself for it.",
    "Someone I loved died because of a mistake I made. That will never happen again.",
    "My instrument is my most treasured possession, and it reminds me of someone I love.",
    "Someone stole my precious instrument, and someday I'll get it back.",
    "I want to be famous, whatever it takes.",
    "I idolize a hero of the old tales and measure my deeds against that person's.",
    "I will do anything to prove myself superior to me hated rival.",
    "I would do anything for the other members of my old troupe.",
    "I have a family, but I have no idea where they are. One day, I hope to see them again.",
    "I worked the land, I love the land, and I will protect the land.",
    "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.",
    "My tools are symbols of my past life, and I carry them so that I will never forget my roots.",
    "I protect those who cannot protect themselves.",
    "I wish my childhood sweetheart had come with me to pursue my destiny.",
    "The workshop where I learned my trade is the most important place in the world to me.",
    "I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.",
    "I owe my guild a great debt for forging me into the person I am today.",
    "I pursue wealth to secure someone's love.",
    "One day I will return to my guild and prove that I am the greatest artisan of them all.",
    "I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.",
    "Nothing is more important than the other members of my hermitage, order, or association.",
    "I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.",
    "I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.",
    "I entered seclusion because I loved someone I could not have.",
    "Should my discovery come to light, it could bring ruin to the world.",
    "My isolation gave me great insight into a great evil that only I can destroy.",
    "I will face any challenge to win the approval of my family.",
    "My house's alliance with another noble family must be sustained at all costs.",
    "Nothing is more important that the other members of my family.",
    "I am in love with the heir of a family that my family despises.",
    "My loyalty to my sovereign is unwavering.",
    "The common folk must see me as a hero of the people.",
    "My family, clan, or tribe is the most important thing in my life, even when they are far from me.",
    "An injury to the unspoiled wilderness of my home is an injury to me.",
    "I will bring terrible wrath down on the evildoers who destroyed my homeland.",
    "I am the last of my tribe, and it is up to me to ensure their names enter legend.",
    "I suffer awful visions of a coming disaster and will do anything to prevent it.",
    "It is my duty to provide children to sustain my tribe.",
    "It is my duty to protect my students.",
    "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.",
    "I work to preserve a library, university, scriptorium, or monastery.",
    "My life's work is a series of tomes related to a specific field of lore.",
    "I've been searching my whole life for the answer to a certain question.",
    "I sold my soul for knowledge. I hope to do great deeds and win it back.",
    "I'm loyal to my captain first, everything else second.",
    "The ship is most important--crewmates and captains come and go.",
    "I'll always remember my first ship.",
    "In a harbor town, I have a paramour whose eyes nearly stole me from the sea.",
    "I was cheated of my fair share of the profits, and I want to get my due.",
    "Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.",
    "I would lay down my life for the people I served with.",
    "Someone saved my life on the battlefield. To this day, I will never leave a friend behind.",
    "My honor is my life.",
    "I'll never forget the crushing defeat my company suffered or the enemies who dealt it.",
    "Those who fight beside me are those worth dying for.",
    "I fight for those who cannot fight for themselves.",
    "My town or city is my home, and I'll fight to defend it.",
    "I sponsor an orphanage to keep others from enduring what I was forced to endure.",
    "I owe my survival to another urchin who taught me to live on the streets.",
    "I owe a debt I can never repay to the person who took pity on me.",
    "I escaped my life of poverty by robbing an important person, and I'm wanted for it.",
]

var flaws = [
    "I judge others harshly, and myself even more severely.",
    "I put too much trust in those who wield power within my temple's hierarchy.",
    "My piety sometimes leads me to blindly trust those that profess faith in my god.",
    "I am inflexible in my thinking.",
    "I am suspicious of strangers and suspect the worst of them.",
    "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.",
    "I can't resist a pretty face.",
    "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.",
    "I'm convinced that no one could ever fool me in the way I fool others.",
    "I'm too greedy for my own good. I can't resist taking a risk if there's money involved.",
    "I can't resist swindling people who are more powerful than me.",
    "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough.",
    "When I see something valuable, I can't think about anything but how to steal it.",
    "When faced with a choice between money and my friends, I usually choose the money.",
    "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.",
    "I have a 'tell' that reveals when I'm lying.",
    "I turn tail and run when things go bad.",
    "An innocent person is in prison for a crime that I committed. I'm okay with that.",
    "I'll do anything to win fame and renown.",
    "I'm a sucker for a pretty face.",
    "A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.",
    "I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.",
    "I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.",
    "Despite my best efforts, I am unreliable to my friends.",
    "The tyrant who rules my land will stop at nothing to see me killed.",
    "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.",
    "The people who knew me when I was young know my shameful secret, so I can never go home again.",
    "I have a weakness for the vices of the city, especially hard drink.",
    "Secretly, I believe that things would be better if I were a tyrant lording over the land.",
    "I have trouble trusting in my allies.",
    "I'll do anything to get my hands on something rare or priceless.",
    "I'm quick to assume that someone is trying to cheat me.",
    "No one must ever learn that I once stole money from guild coffers.",
    "I'm never satisfied with what I have--I always want more.",
    "I would kill to acquire a noble title.",
    "I'm horribly jealous of anyone who outshines my handiwork. Everywhere I go, I'm surrounded by rivals.",
    "Now that I've returned to the world, I enjoy its delights a little too much.",
    "I harbor dark bloodthirsty thoughts that my isolation failed to quell.",
    "I am dogmatic in my thoughts and philosophy.",
    "I let my need to win arguments overshadow friendships and harmony.",
    "I'd risk too much to uncover a lost bit of knowledge.",
    "I like keeping secrets and won't share them with anyone.",
    "I secretly believe that everyone is beneath me.",
    "I hide a truly scandalous secret that could ruin my family forever.",
    "I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.",
    "I have an insatiable desire for carnal pleasures.",
    "In fact, the world does revolve around me.",
    "By my words and actions, I often bring shame to my family.",
    "I am too enamored of ale, wine, and other intoxicants.",
    "There's no room for caution in a life lived to the fullest.",
    "I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.",
    "I am slow to trust members of other races",
    "Violence is my answer to almost any challenge.",
    "Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.",
    "I am easily distracted by the promise of information.",
    "Most people scream and run when they see a demon. I stop and take notes on its anatomy.",
    "Unlocking an ancient mystery is worth the price of a civilization.",
    "I overlook obvious solutions in favor of complicated ones.",
    "I speak without really thinking through my words, invariably insulting others.",
    "I can't keep a secret to save my life, or anyone else's.",
    "I follow orders, even if I think they're wrong.",
    "I'll say anything to avoid having to do extra work.",
    "Once someone questions my courage, I never back down no matter how dangerous the situation.",
    "Once I start drinking, it's hard for me to stop.",
    "I can't help but pocket loose coins and other trinkets I come across.",
    "My pride will probably lead to my destruction",
    "The monstrous enemy we faced in battle still leaves me quivering with fear.",
    "I have little respect for anyone who is not a proven warrior.",
    "I made a terrible mistake in battle that cost many lives--and I would do anything to keep that mistake secret.",
    "My hatred of my enemies is blind and unreasoning.",
    "I obey the law, even if the law causes misery.",
    "I'd rather eat my armor than admit when I'm wrong.",
    "If I'm outnumbered, I always run away from a fight.",
    "Gold seems like a lot of money to me, and I'll do just about anything for more of it.",
    "I will never fully trust anyone other than myself.",
    "I'd rather kill someone in their sleep than fight fair.",
    "It's not stealing if I need it more than someone else.",
]

var maleFirstnames = [
    "Elvis",
    "Lawson",
    "Ronin",
    "Braiden",
    "Kevin",
    "Finnegan",
    "Yosef",
    "Axel",
    "Jordyn",
    "Hudson",
    "Javon",
    "Chaim",
    "Aedan",
    "Leon",
    "Grant",
    "Nico",
    "Salvatore",
    "Alan",
    "Gunnar",
    "Darryl",
    "Joe",
    "Kingston",
    "Ruben",
    "Nelson",
    "Ross",
    "Tyler",
    "Asher",
    "Josiah",
    "Darnell",
    "Frederick",
    "Alejandro",
    "Leandro",
    "Terrance",
    "Randy",
    "Fernando",
    "Ishaan",
    "Craig",
    "Malcolm",
    "Brent",
    "Larry",
    "Fisher",
    "Robert",
    "Richard",
    "Wyatt",
    "Giovani",
    "Zaire",
    "Dominick",
    "Yusuf",
    "Darius",
    "Konner",
    "Dario",
    "Gideon",
    "Trevor",
    "Yurem",
    "Adolfo",
    "Bentley",
    "Kolton",
    "Nolan",
    "Atticus",
    "Alexander",
    "Conner",
    "Jeramiah",
    "Zain",
    "Jean",
    "Kyan",
    "Adam",
    "Ahmad",
    "Paul",
    "Dorian",
    "Chris",
    "Jaxon",
    "Tyson",
    "Finley",
    "Clay",
    "Cristian",
    "Cayden",
    "Jaidyn",
    "Samson",
    "Graham",
    "Layton",
    "Joshua",
    "Conor",
    "Octavio",
    "Warren",
    "Dax",
    "Braden",
    "Vicente",
    "Todd",
    "Anton",
    "Jason",
    "Skylar",
    "Alex",
    "Jaylen",
    "Jairo",
    "Quinn",
    "Eli",
    "Theodore",
    "Isai",
    "Salvador",
    "Nehemiah",
    "Elijah",
    "Blake",
    "Korbin",
    "Nicolas",
    "Koen",
    "Quentin",
    "Yair",
    "Memphis",
    "Cannon",
    "Justice",
    "Mekhi",
    "Sammy",
    "Carsen",
    "Adrien",
    "Messiah",
    "Bryan",
    "Leland",
    "Danny",
    "Demarion",
    "Reynaldo",
    "Nikolai",
    "Francis",
    "Morgan",
    "Julian",
    "Jalen",
    "Dominic",
    "Ezekiel",
    "Javion",
    "Jamie",
    "Nathanael",
    "Hamza",
    "Cullen",
    "Mohamed",
    "Raiden",
    "Desmond",
    "Harley",
    "Micah",
    "Nickolas",
    "Aaron",
    "Josh",
    "Albert",
    "Chance",
    "Ray",
    "Isaac",
    "Joseph",
    "Tommy",
    "Noe",
    "Jase",
    "Kyler",
    "Peter",
    "Clinton",
    "Hassan",
    "Harrison",
    "Geovanni",
    "Blaine",
    "Pedro",
    "Carson",
    "Darwin",
    "Manuel",
    "Titus",
    "George",
    "Aydan",
    "Beckett",
    "Matthias",
    "Semaj",
    "Joey",
    "Aarav",
    "Kobe",
    "Caleb",
    "Reginald",
    "Conrad",
    "Byron",
    "Nikolas",
    "Jaydin",
    "Jovanni",
    "Yahir",
    "Cedric",
    "Santos",
    "Pranav",
    "Kenyon",
    "Alonso",
    "Marcus",
    "Muhammad",
    "Eduardo",
    "Armani",
    "Drake",
    "Efrain",
    "Willie",
    "Jermaine",
    "Zayne",
    "King",
    "Carmelo",
    "Jaron",
    "Nasir",
    "Sullivan",
    "Francisco",
    "Armando",
    "Marques",
    "Rashad",
    "Malakai",
    "Collin",
    "Gary",
    "Kayden",
    "Darion",
    "Brendon",
    "Kenneth",
    "Barrett",
    "Beckham",
    "Ethen",
    "Devin",
    "Alfredo",
    "Aldo",
    "Zane",
    "Brice",
    "Brandon",
    "Jamir",
    "Phillip",
    "Fabian",
    "Jonas",
    "Bailey",
    "Ronan",
    "Madden",
    "Chandler",
    "Jeffery",
    "Antonio",
    "Esteban",
    "Jesse",
    "Fletcher",
    "Jace",
    "Agustin",
    "Giancarlo",
    "Winston",
    "Ali",
    "Guillermo",
    "Riley",
    "Jerome",
    "Jeremy",
    "Kamron",
    "Cale",
    "Cory",
    "Cassius",
    "Hunter",
    "Dylan",
    "Jamari",
    "Stanley",
    "Trenton",
    "Luka",
    "Kole",
    "Vaughn",
    "Kamden",
    "Chace",
    "Edward",
    "Nash",
    "Dennis",
    "Zachary",
    "Reece",
    "Judah",
    "Yadiel",
    "Chad",
    "Cash",
    "Shawn",
    "Dallas",
    "Remington",
    "Gilberto",
    "Levi",
    "Ahmed",
    "Eugene",
    "Carlos",
    "Donavan",
    "Krish",
    "Asa",
    "Hayden",
    "Arturo",
    "Roman",
    "Simeon",
    "Elliott",
    "Lawrence",
    "Reese",
    "Makai",
    "Jadiel",
    "Elliot",
    "Mario",
    "Hugh",
    "Odin",
    "Shaun",
    "Cyrus",
    "Oliver",
    "Jadon",
    "Aidan",
    "Alec",
    "Oswaldo",
    "Killian",
    "Brenden",
    "Justus",
    "Grayson",
    "Ernest",
    "Emerson",
    "Cole",
    "Ricky",
    "Dexter",
    "Layne",
    "Lucas",
    "Abel",
    "Moshe",
    "Allen",
    "Emanuel",
    "Maddox",
    "Zachariah",
    "Joel",
    "Braylen",
    "Davis",
    "Gustavo",
    "Gaige",
    "Timothy",
    "Enrique",
    "Cody",
    "Ryder",
    "Roger",
    "Tristian",
    "Jabari",
    "Keegan",
    "Bradyn",
    "Damari",
    "Zackery",
    "Cameron",
    "Zack",
    "Taylor",
    "Jaydan",
    "Dante",
    "Ronnie",
    "Rory",
    "Jayson",
    "Franco",
    "Pierce",
    "Bobby",
    "Devon",
    "Ignacio",
    "Kasen",
    "Raphael",
    "Alvaro",
    "Johnny",
    "Zavier",
    "Thaddeus",
    "Javier",
    "Camren",
    "Valentino",
    "Damarion",
    "Logan",
    "James",
    "Lyric",
    "Braydon",
    "Frankie",
    "Skyler",
    "Isaias",
    "Houston",
    "Israel",
    "Jaime",
    "Amari",
    "Easton",
    "Luca",
    "Van",
    "Adan",
    "Gael",
    "Cooper",
    "Alexis",
    "Christian",
    "Lukas",
    "Cortez",
    "Zaiden",
    "Jeffrey",
    "Kasey",
    "Jovan",
    "Yael",
    "Kyle",
    "Jerimiah",
    "Ryland",
    "William",
    "Bennett",
    "Leonidas",
    "Rodrigo",
    "Damien",
    "Jasper",
    "Colby",
    "Douglas",
    "Sawyer",
    "Jamarcus",
    "Cornelius",
    "Weston",
    "Amir",
    "Andrew",
    "Sage",
    "Keith",
    "Issac",
    "Nikhil",
    "Ismael",
    "Gilbert",
    "Giovanny",
    "Omari",
    "Maxwell",
    "Demetrius",
    "Samuel",
    "Jacob",
    "Orion",
    "Kendall",
    "Roy",
    "Jovanny",
    "Jimmy",
    "Broderick",
    "Ashton",
    "Sam",
    "Callum",
    "Orlando",
    "Jon",
    "Kai",
    "Wilson",
    "Ean",
    "Lance",
    "Brayden",
    "Rylan",
    "Pierre",
    "Nicholas",
    "Deshawn",
    "Santino",
    "Julius",
    "Myles",
    "Triston",
    "Ralph",
    "Davon",
    "Seth",
    "Emiliano",
    "Rhys",
    "Ronald",
    "Colten",
    "Lorenzo",
    "Rex",
    "Jaquan",
    "Roderick",
    "David",
    "Trace",
    "Charles",
    "Alvin",
    "Wesley",
    "Rocco",
    "Tripp",
    "Khalil",
    "Johnathon",
    "Eden",
    "Marc",
    "Karson",
    "Carter",
    "Addison",
    "Evan",
    "Slade",
    "Jan",
    "Tyrese",
    "Oscar",
    "Walter",
    "Jacoby",
    "Daniel",
    "Jaylan",
    "Edwin",
    "Derrick",
    "Lennon",
    "Kody",
    "Philip",
    "Rafael",
    "Calvin",
    "Giovanni",
    "Markus",
    "Kareem",
    "Finn",
    "Aditya",
    "Marcel",
    "Rey",
    "Leo",
    "Malik",
    "Dustin",
    "Josue",
    "Brayan",
    "Jude",
    "Jackson",
    "Jaxson",
    "Scott",
    "Darrell",
    "Julio",
    "Leonel",
    "Brady",
    "Arthur",
    "Jake",
    "London",
    "Landin",
    "Gunner",
    "Kaiden",
    "Cesar",
    "Brogan",
    "Sonny",
    "Adriel",
    "Trey",
    "Bryson",
    "Emmett",
    "Marco",
    "Kolten",
    "Gregory",
    "Xzavier",
    "Rayan",
    "Case",
    "Soren",
    "Maxim",
    "Aryan",
    "Dillan",
    "Kadyn",
    "Wayne",
    "Brooks",
    "Keyon",
    "Jagger",
    "Dalton",
    "Kash",
    "Charlie",
    "Benjamin",
    "Keon",
    "Anderson",
    "Bradley",
    "Deven",
    "Jakobe",
    "Moises",
    "Tristin",
    "Kameron",
    "Kieran",
    "Donald",
    "Zayden",
    "Harold",
    "Henry",
    "Damon",
    "Makhi",
    "Zackary",
    "Reed",
    "Hugo",
    "Anthony",
    "Nick",
    "Lee",
    "Ulises",
    "Tate",
    "Hezekiah",
    "Trevon",
    "Diego",
    "Keaton",
    "Dangelo",
    "Ezra",
    "Eric",
    "Walker",
    "Rylee",
    "Reuben",
    "Bronson",
    "Stephen",
    "Russell",
    "Talon",
    "Mike",
    "Casey",
    "Romeo",
    "Avery",
    "Dominique",
    "Nathan",
    "Davion",
    "Camryn",
    "Payton",
    "Alonzo",
    "Augustus",
    "Sidney",
    "Sincere",
    "Caiden",
    "Branson",
    "Zion",
    "Saul",
    "Raymond",
    "Branden",
    "Noah",
    "Simon",
    "German",
    "Ayaan",
    "Rishi",
    "Zechariah",
    "Tristan",
    "Juan",
    "August",
    "Ivan",
    "Uriel",
    "Maurice",
    "Nathanial",
    "Mark",
    "Martin",
    "Darren",
    "Kason",
    "Rowan",
    "Mateo",
    "Jett",
    "Brock",
    "Blaze",
    "Edgar",
    "Reilly",
    "Brendan",
]


var femaleFirstnames = [
    "Jaslyn",    
    "Monserrat",
    "Evelin",   
    "Livia",    
    "Jaylen",   
    "Rhianna",  
    "Hayley",   
    "Scarlett", 
    "Sophia",   
    "Xiomara",  
    "Izabella", 
    "Aliza",    
    "Alissa",
    "Justice",
    "Penelope",
    "Celeste",
    "Ryan",
    "Lizeth",
    "Maren",
    "Nevaeh",
    "Abigayle",
    "Natalie",
    "Maci",
    "Liana",
    "Karma",
    "Giuliana",
    "Kaydence",
    "Rayna",
    "Selina",
    "Tia",
    "Allison",
    "Denisse",
    "Saige",
    "Paula",
    "Karlee",
    "Campbell",
    "Shelby",
    "Raven",
    "Kaleigh",
    "Alivia",
    "Adrianna",
    "Amaris",
    "Corinne",
    "Andrea",
    "Regina",
    "Cloe",
    "Bailee",
    "Aimee",
    "Olive",
    "Kendra",
    "Maeve",
    "Eden",
    "Madelynn",
    "Skylar",
    "Adalyn",
    "Rubi",
    "Jessie",
    "Theresa",
    "Gianna",
    "Kaitlynn",
    "Denise",
    "Julianna",
    "Tamara",
    "Miracle",
    "Taylor",
    "Lily",
    "Alani",
    "Averi",
    "Fernanda",
    "Ana",
    "Amiyah",
    "Thalia",
    "Camila",
    "Brylee",
    "Elianna",
    "Shaylee",
    "Marlene",
    "Susan",
    "Kaya",
    "Kaliyah",
    "Tamia",
    "Giselle",
    "Yaritza",
    "Angel",
    "Emerson",
    "Jacquelyn",
    "Talia",
    "Addyson",
    "Shyla",
    "Quinn",
    "Lydia",
    "Abigail",
    "Marely",
    "Sariah",
    "Angeline",
    "Aurora",
    "Jaidyn",
    "Luz",
    "Kaila",
    "Lesly",
    "Mayra",
    "Yareli",
    "Sidney",
    "Danielle",
    "Hillary",
    "Isabell",
    "Frida",
    "Jaylin",
    "Shea",
    "Courtney",
    "April",
    "Lillie",
    "Riley",
    "Jamie",
    "Michelle",
    "Kennedy",
    "Jasmine",
    "Tatiana",
    "Annika",
    "Averie",
    "Mylee",
    "Ellie",
    "Bethany",
    "Jayleen",
    "Macy",
    "Gwendolyn",
    "Logan",
    "Jenny",
    "Jaida",
    "Paris",
    "Kendall",
    "Genesis",
    "Cameron",
    "Stephany",
    "Iyana",
    "Sophie",
    "Dayami",
    "Christina",
    "Jennifer",
    "Micaela",
    "Ainsley",
    "Alexandra",
    "Jazmyn",
    "Jessica",
    "Kamora",
    "Journey",
    "Daniela",
    "Jordan",
    "Kaelyn",
    "Sydney",
    "Ruby",
    "Jaslene",
    "Meadow",
    "Deja",
    "Karli",
    "Sandra",
    "Katie",
    "Eliza",
    "Jolie",
    "Alisa",
    "Janiah",
    "Adriana",
    "Mireya",
    "Desiree",
    "Cali",
    "Chasity",
    "Lucille",
    "Eliana",
    "Laylah",
    "Alondra",
    "Armani",
    "Emery",
    "Miriam",
    "Jaylene",
    "Madisyn",
    "Taniyah",
    "Amirah",
    "Makena",
    "Magdalena",
    "Joselyn",
    "Jane",
    "Libby",
    "Destiney",
    "Kassandra",
    "Jaylyn",
    "Gillian",
    "Britney",
    "Ashlynn",
    "Natalee",
    "Miah",
    "Kadence",
    "Lyric",
    "Kali",
    "Hana",
    "Juliana",
    "Aryana",
    "Aubree",
    "Mila",
    "Jaelynn",
    "Eve",
    "Tiara",
    "Gabriela",
    "Rosemary",
    "Emely",
    "Sanaa",
    "Summer",
    "Jaylah",
    "Gracelyn",
    "Cecelia",
    "Lexi",
    "Carlee",
    "Donna",
    "Gisselle",
    "Faith",
    "Kinley",
    "Ariana",
    "Leyla",
    "Anna",
    "Lizbeth",
    "Laura",
    "Tanya",
    "Eva",
    "Clara",
    "Danika",
    "Crystal",
    "Marlee",
    "Isabel",
    "Victoria",
    "Sarah",
    "Julianne",
    "Alayna",
    "Catalina",
    "Kiera",
    "Anahi",
    "Mckinley",
    "Kennedi",
    "Meghan",
    "Tabitha",
    "Peyton",
    "Vivian",
    "Charlize",
    "Sanai",
    "Amani",
    "Jordin",
    "Carlie",
    "Kayla",
    "Megan",
    "Estrella",
    "Aisha",
    "Patience",
    "Athena",
    "Patricia",
    "Matilda",
    "Katrina",
    "Dayana",
    "Kassidy",
    "Marlie",
    "Teresa",
    "Janiya",
    "Angelica",
    "Roselyn",
    "Hadley",
    "Ciara",
    "Shyann",
    "Gloria",
    "Tiana",
    "Angie",
    "Raegan",
    "Reagan",
    "Milagros",
    "Carleigh",
    "Aleah",
    "Natalia",
    "Lilianna",
    "Charlie",
    "Makenna",
    "Lina",
    "Miley",
    "Elsie",
    "Rebekah",
    "Clarissa",
    "Rachel",
    "Amari",
    "Sara",
    "Rosa",
    "Anastasia",
    "Selena",
    "Cindy",
    "Zoey",
    "Alexia",
    "Moriah",
    "Mikaela",
    "Kimora",
    "Briley",
    "Lainey",
    "Sylvia",
    "Brenna",
    "Diana",
    "Amanda",
    "Yazmin",
    "Maggie",
    "Madalynn",
    "Valerie",
    "Lena",
    "Ally",
    "Riya",
    "Janae",
    "Mariyah",
    "Lindsey",
    "Aria",
    "Elisabeth",
    "Brianna",
    "Ingrid",
    "Jazmine",
    "Dylan",
    "Diya",
    "Mariana",
    "Kaylie",
    "Kianna",
    "Janet",
    "Adyson",
    "Linda",
    "Alison",
    "Krista",
    "Kendal",
    "Reyna",
    "Jaden",
    "Georgia",
    "Cassandra",
    "Pamela",
    "Angelique",
    "Jewel",
    "Giada",
    "Savannah",
    "Yoselin",
    "Shania",
    "Tianna",
    "Valery",
    "Daniella",
    "Jaliyah",
    "Kasey",
    "Daisy",
    "Layla",
    "Shyanne",
    "Sarahi",
    "Perla",
    "Evie",
    "Haleigh",
    "Brooklyn",
    "Areli",
    "Kailyn",
    "Aaliyah",
    "Kelsey",
    "Lillian",
    "Brittany",
    "Jadyn",
    "Makenzie",
    "Chanel",
    "Kierra",
    "Rayne",
    "Deanna",
    "Monique",
    "Trinity",
    "Karla",
    "Paige",
    "Jacqueline",
    "Sabrina",
    "Esperanza",
    "Bailey",
    "Abril",
    "Alina",
    "Alexandria",
    "Lara",
    "Alena",
    "Annalise",
    "Essence",
    "Jakayla",
    "Harmony",
    "Kenzie",
    "Kate",
    "Harper",
    "Kaylin",
    "Taliyah",
    "Giovanna",
    "Makaila",
    "Jimena",
    "Isla",
    "Paola",
    "Bria",
    "Jamiya",
    "Kelsie",
    "Amiya",
    "Arely",
    "Kinsley",
    "Alisha",
    "Myah",
    "Lauren",
    "Jazlyn",
    "Kiana",
    "Fatima",
    "Melody",
    "Leanna",
    "Erin",
    "Heaven",
    "Gretchen",
    "Giana",
    "Leia",
    "Heidi",
    "Mia",
    "Keira",
    "Ireland",
    "Ashtyn",
    "Gemma",
    "Lexie",
    "Amira",
    "Ayanna",
    "Itzel",
    "Carolina",
    "Bridget",
    "Yadira",
    "Abby",
    "Viviana",
    "Genevieve",
    "Addisyn",
    "Briana",
    "Lorelei",
    "Annabella",
    "Ella",
    "Callie",
    "Morgan",
    "Sharon",
    "Jaiden",
    "Karley",
    "Camryn",
    "Nylah",
    "Nadia",
    "Marisa",
    "Isis",
    "Dayanara",
    "Saniya",
    "Amya",
    "Emmalee",
    "Jayden",
    "Marie",
    "Kaylynn",
    "Cheyenne",
    "Rowan",
    "Saniyah",
    "Noelle",
    "Dakota",
    "Maddison",
    "Rebecca",
    "Katelynn",
    "Phoebe",
    "Nathaly",
    "Justine",
    "Edith",
    "Chloe",
    "Khloe",
    "Nathalia",
    "Evelyn",
    "Neveah",
    "Abagail",
    "Kiley",
    "Josephine",
    "Lucy",
    "Arianna",
    "Mackenzie",
    "Karlie",
    "Chaya",
    "Rose",
    "Litzy",
    "Monica",
    "Olivia",
    "Malia",
    "Yuliana",
    "Jamya",
    "Julia",
    "Mary",
    "Alia",
    "Kaylee",
    "Madalyn",
    "Melissa",
    "Aspen",
    "Tania",
    "Scarlet",
    "Madilyn",
    "Skyla",
    "Damaris",
    "Samara",
    "Shiloh",
    "Marin",
    "Princess",
    "Londyn",
    "Ann",
    "Madison",
    "Maritza",
    "Macie",
    "Noemi",
    "Lorena",
    "Dania",
    "Brooke",
    "Haylie",
    "Gina",
    "Joyce",
    "Guadalupe",
    "Laci",
    "Avah",
    "Ashlee",
    "Melanie",
    "Selah",
    "Maya",
    "Haley",
    "Anaya",
    "Casey",
    "Sierra",
    "Hope",
    "Elaine",
    "Ashlyn",
    "Elyse",
    "Kamryn",
    "Nia",
    "Annabel",
    "Esmeralda",
    "Emilie",
    "Isabela",
    "Yasmine",
    "Katherine",
    "Alannah",
    "Lana",
    "Marissa",
    "Nathalie",
    "Simone",
    "Teagan",
    "Adelaide",
    "Alyson",
    "Allisson",
    "Kara",
    "Cecilia",
    "Keely",
    "Serena",
    "Lucia",
    "Paityn",
    "Kailee",
    "Elliana",
    "Lisa",
    "Kaley",
    "Belinda",
    "Margaret",
    "Renee",
    "Nyla",
    "Gabrielle",
    "Avery",
    "Lilia",
    "Kathleen",
    "Jillian",
    "Mina",
    "Carley",
    "Rylee",
    "Leslie",
    "Natasha",
    "Yamilet",
    "Greta",
    "Finley",
    "Brenda",
    "Marley",
    "Daphne",
    "Kathy",
    "Miya",
    "Raina",
    "Shayla",
    "Adeline",
    "Alisson",
    "Sherlyn",
    "Nola",
    "Aliya",
    "Willow",
    "Brisa",
    "Destiny",
    "Kaylyn",
    "Salma",
    "Kayden",
    "Emilia",
    "Kamari",
    "Charlotte",
    "Norah",
    "Akira",
    "Marilyn",
    "Martha",
    "Dana",
    "Celia",
    "Danica",
    "Amina",
    "Anabelle",
    "Anabella",
    "Raquel",
    "Jaylynn",
    "Ximena",
    "Tara",
    "Maliyah",
]

var lastnames = [
    "Gilmore",   
    "Santiago", 
    "Mata",     
    "Cantrell", 
    "Schroeder",
    "Velasquez",
    "Serrano",  
    "Schultz",  
    "Le",       
    "Mccann",   
    "Glover",   
    "Hendrix",  
    "Cross",
    "Pace",
    "Huffman",
    "Booker",
    "Morton",
    "Newman",
    "Macias",
    "Vincent",
    "Lynch",
    "Robertson",
    "Blackburn",
    "Harding",
    "Giles",
    "Wyatt",
    "Ashley",
    "Norris",
    "Bowman",
    "Vasquez",
    "Yates",
    "Mason",
    "Hooper",
    "Price",
    "Tran",
    "Huber",
    "Owen",
    "Grimes",
    "Berger",
    "Singh",
    "Hill",
    "Aguilar",
    "Travis",
    "Kaiser",
    "Clarke",
    "Rangel",
    "Cunningham",
    "Hester",
    "Mann",
    "Jefferson",
    "Parker",
    "Moore",
    "Wu",
    "Armstrong",
    "Fisher",
    "Page",
    "Valenzuela",
    "Goodwin",
    "Beck",
    "Holland",
    "Casey",
    "Kramer",
    "Bean",
    "Hudson",
    "Wolf",
    "Petersen",
    "Davies",
    "Boone",
    "Waters",
    "Kemp",
    "Chung",
    "Mercer",
    "Conway",
    "Day",
    "Wilson",
    "Abbott",
    "Booth",
    "Aguirre",
    "Nunez",
    "Madden",
    "Davis",
    "Maxwell",
    "Hernandez",
    "Meyers",
    "Leblanc",
    "Anderson",
    "Stanton",
    "Patton",
    "Gould",
    "Marks",
    "Bright",
    "Alvarado",
    "Riggs",
    "Warner",
    "Turner",
    "Hawkins",
    "Downs",
    "Mccarty",
    "Owens",
    "Odonnell",
    "Newton",
    "Copeland",
    "Mcclain",
    "Figueroa",
    "Meza",
    "Morris",
    "Cameron",
    "Mckay",
    "Friedman",
    "Yang",
    "Everett",
    "Johns",
    "Mercado",
    "Bowen",
    "Barrera",
    "Levine",
    "Calderon",
    "Dickson",
    "Vega",
    "Riley",
    "Bryant",
    "Coffey",
    "Walls",
    "Pacheco",
    "Maddox",
    "Melendez",
    "Lewis",
    "Powell",
    "Mathis",
    "Boyd",
    "Leach",
    "Hubbard",
    "Tate",
    "Duke",
    "Larson",
    "Floyd",
    "Roman",
    "Hardin",
    "Nicholson",
    "Little",
    "Richards",
    "Griffith",
    "Dyer",
    "Tyler",
    "Malone",
    "Logan",
    "Rojas",
    "Harrell",
    "Nguyen",
    "Hampton",
    "Stephens",
    "Howell",
    "Clay",
    "Davenport",
    "Rubio",
    "Kent",
    "Noble",
    "Curry",
    "Mccullough",
    "Gordon",
    "Barber",
    "Montes",
    "Gibbs",
    "Briggs",
    "Ray",
    "Frye",
    "Tucker",
    "Hines",
    "Rosales",
    "Jackson",
    "Elliott",
    "Conrad",
    "Mclean",
    "Velez",
    "Hoffman",
    "Weaver",
    "Bowers",
    "Cardenas",
    "Schaefer",
    "Crane",
    "Gentry",
    "Vang",
    "Archer",
    "Costa",
    "Garner",
    "Lynn",
    "Kirk",
    "Soto",
    "Fernandez",
    "Massey",
    "Irwin",
    "Li",
    "Oconnell",
    "May",
    "Richmond",
    "Snyder",
    "Stuart",
    "Gray",
    "Castro",
    "Sandoval",
    "Moss",
    "Cochran",
    "Boyer",
    "Hunter",
    "Trevino",
    "Zuniga",
    "Atkins",
    "Mcbride",
    "Good",
    "Webster",
    "Sloan",
    "Freeman",
    "Mullins",
    "Cline",
    "Arnold",
    "Compton",
    "Strong",
    "Coleman",
    "Leon",
    "Spence",
    "Blevins",
    "Mclaughlin",
    "Savage",
    "Petty",
    "Fleming",
    "Norton",
    "Bernard",
    "Marquez",
    "Knapp",
    "Cervantes",
    "Strickland",
    "Buck",
    "Delgado",
    "Spencer",
    "Hanson",
    "Silva",
    "Diaz",
    "Cox",
    "Jones",
    "Guerrero",
    "Martin",
    "Cole",
    "Saunders",
    "Lane",
    "Fry",
    "Wang",
    "Sutton",
    "Guzman",
    "Park",
    "Mccall",
    "Lutz",
    "Gillespie",
    "Brennan",
    "Mora",
    "Ortiz",
    "Lyons",
    "Duarte",
    "Banks",
    "Wolfe",
    "Barajas",
    "Whitehead",
    "Farrell",
    "King",
    "Franco",
    "Mack",
    "Craig",
    "Frank",
    "Frost",
    "Navarro",
    "Woodward",
    "Collins",
    "Quinn",
    "Mayer",
    "Sanders",
    "Hunt",
    "Lozano",
    "Terry",
    "Mcmillan",
    "Henderson",
    "Dillon",
    "Robinson",
    "Solis",
    "Rose",
    "Pruitt",
    "Nichols",
    "Mcgee",
    "Benjamin",
    "Brooks",
    "Cooper",
    "Carson",
    "James",
    "Bray",
    "Zhang",
    "Macdonald",
    "Peters",
    "Flowers",
    "Camacho",
    "Stokes",
    "Shepherd",
    "Small",
    "Decker",
    "Barton",
    "Ferrell",
    "Blake",
    "Colon",
    "Fletcher",
    "Yu",
    "Humphrey",
    "Cummings",
    "Sims",
    "Mejia",
    "Wells",
    "Gross",
    "Valentine",
    "Pham",
    "Johnston",
    "Hayes",
    "Baldwin",
    "Stout",
    "Holden",
    "Nash",
    "Stafford",
    "Summers",
    "Walter",
    "Lindsey",
    "Potter",
    "Olsen",
    "Mueller",
    "Mathews",
    "Rice",
    "Watts",
    "Deleon",
    "Montgomery",
    "Moses",
    "Walker",
    "Sullivan",
    "Evans",
    "Ford",
    "Shah",
    "Erickson",
    "Williamson",
    "Schwartz",
    "Mcdaniel",
    "Franklin",
    "Stephenson",
    "Gregory",
    "Estes",
    "Mccarthy",
    "Barker",
    "Dougherty",
    "Chapman",
    "Werner",
    "Francis",
    "Walton",
    "Hancock",
    "Cohen",
    "Kennedy",
    "Bond",
    "Simon",
    "Dickerson",
    "Ewing",
    "Schneider",
    "Blackwell",
    "Haynes",
    "Merritt",
    "Kane",
    "Forbes",
    "George",
    "Manning",
    "Vance",
    "Ochoa",
    "Austin",
    "Rivera",
    "Rhodes",
    "Bender",
    "Carney",
    "Conley",
    "Kidd",
    "Phillips",
    "Morgan",
    "Escobar",
    "Rollins",
    "Wiggins",
    "Green",
    "Stein",
    "Hall",
    "Wong",
    "Richard",
    "Parks",
    "Villarreal",
    "Gardner",
    "Lopez",
    "Willis",
    "Conner",
    "Goodman",
    "Mcknight",
    "Maldonado",
    "Shannon",
    "Fuentes",
    "Montoya",
    "Curtis",
    "Durham",
    "Cisneros",
    "Novak",
    "Schmidt",
    "Greene",
    "Hutchinson",
    "Houston",
    "Underwood",
    "Bolton",
    "Carter",
    "Townsend",
    "Landry",
    "Marshall",
    "Garza",
    "Pearson",
    "Sanford",
    "Garcia",
    "Gilbert",
    "Black",
    "Poole",
    "Cain",
    "Proctor",
    "Sheppard",
    "Palmer",
    "Espinoza",
    "Preston",
    "Rowe",
    "Ho",
    "Oneal",
    "Rich",
    "Wall",
    "Chavez",
    "Mcneil",
    "Dominguez",
    "Branch",
    "Heath",
    "Medina",
    "Klein",
    "Bates",
    "Salazar",
    "Terrell",
    "Hickman",
    "Case",
    "Ellis",
    "Harrington",
    "Murphy",
    "Bradford",
    "Ellison",
    "Christian",
    "Jensen",
    "Arias",
    "Zimmerman",
    "Pratt",
    "Boyle",
    "Ponce",
    "Cabrera",
    "Perry",
    "Richardson",
    "Mullen",
    "Simmons",
    "Mcpherson",
    "Dalton",
    "Greer",
    "Carrillo",
    "Fox",
    "Graves",
    "Lin",
    "Luna",
    "Bruce",
    "Miranda",
    "Stanley",
    "Vargas",
    "Zavala",
    "Pugh",
    "Clayton",
    "Mcdonald",
    "Larsen",
    "Campos",
    "Gay",
    "Mills",
    "Kline",
    "Caldwell",
    "Kaufman",
    "Calhoun",
    "Burton",
    "Rodriguez",
    "Grant",
    "Huang",
    "Hinton",
    "Moyer",
    "Brady",
    "Hensley",
    "Church",
    "Roth",
    "Russell",
    "Shelton",
    "Krueger",
    "Chaney",
    "Carey",
    "Horton",
    "Keller",
    "Hebert",
    "Sawyer",
    "Huerta",
    "Sampson",
    "Sweeney",
    "Wood",
    "Garrett",
    "Woodard",
    "Andrade",
    "Pena",
    "Patterson",
    "Bishop",
    "Duffy",
    "Jennings",
    "Neal",
    "Marsh",
    "Ware",
    "Mcintosh",
    "Levy",
    "Todd",
    "Rivas",
    "Suarez",
    "Choi",
    "Young",
    "Gallagher",
    "Bradley",
    "Hahn",
    "Frazier",
    "Bentley",
    "Avila",
    "Baxter",
    "Moran",
    "Mcguire",
    "Kirby",
    "Peck",
    "Melton",
    "Gaines",
    "Galloway",
    "Byrd",
    "Cook",
    "Fritz",
    "Potts",
    "Christensen",
    "Wiley",
    "Rivers",
    "Odom",
    "Obrien",
    "Cooke",
    "Vazquez",
    "Krause",
    "Herring",
    "Parrish",
    "Skinner",
    "Hanna",
    "Valdez",
    "Santos",
    "Fitzpatrick",
    "Weiss",
    "Lester",
    "Mckinney",
    "Campbell",
    "Joseph",
    "Burke",
    "Holt",
    "Jacobson",
    "Stevens",
    "Salas",
    "Farmer",
    "Mcmahon",
    "Swanson",
    "Bennett",
    "Galvan",
    "Holmes",
    "Lawrence",
    "Oneill",
    "Dawson",
    "Foster",
    "Carr",
    "Nelson",
    "Stewart",
    "Acosta",
    "Hicks",
    "Long",
    "Murray",
    "Anthony",
    "Morrison",
    "Graham",
    "Wade",
    "Nielsen",
    "Horn",
    "Mahoney",
    "Phelps",
    "Castaneda",
    "Miles",
    "Barry",
    "Foley",
    "Harper",
    "Dean",
]



var spells = [
    "Acid Arrow",
    "Acid Splash",
    "Aid",
    "Alarm",
    "Alter Self",
    "Animal Friendship",    
    "Animal Messenger",     
    "Animal Shapes",        
    "Animate Dead",
    "Animate Objects",      
    "Antilife Shell",       
    "Antimagic Field",      
    "Antipathy/Sympathy",   
    "Arcane Eye",
    "Arcane Hand",
    "Arcane Lock",
    "Arcane Sword",
    "Arcanist's Magic Aura",
    "Astral Projection",    
    "Augury",
    "Awaken",
    "Bane",
    "Banishment",
    "Barkskin",
    "Beacon of Hope",       
    "Bestow Curse",
    "Black Tentacles",
    "Blade Barrier",
    "Bless",
    "Blight",
    "Blindness/Deafness",
    "Blink",
    "Blur",
    "Branding Smite",
    "Burning Hands",
    "Call Lightning",
    "Calm Emotions",
    "Chain Lightning",
    "Charm Person",
    "Chill Touch",
    "Circle of Death",
    "Clairvoyance",
    "Clone",
    "Cloudkill",
    "Color Spray",
    "Command",
    "Commune",
    "Commune with Nature",
    "Comprehend Languages",
    "Compulsion",
    "Cone of Cold",
    "Confusion",
    "Conjure Animals",
    "Conjure Celestial",
    "Conjure Elemental",
    "Conjure Fey",
    "Conjure Minor Elementals",
    "Conjure Woodland Beings",
    "Contact Other Plane",
    "Contagion",
    "Contingency",
    "Continual Flame",
    "Control Water",
    "Control Weather",
    "Counterspell",
    "Create Food and Water",
    "Create Undead",
    "Create or Destroy Water",
    "Creation",
    "Cure Wounds",
    "Dancing Lights",
    "Darkness",
    "Darkvision",
    "Daylight",
    "Death Ward",
    "Delayed Blast Fireball",
    "Demiplane",
    "Detect Evil and Good",
    "Detect Magic",
    "Detect Poison and Disease",
    "Detect Thoughts",
    "Dimension Door",
    "Disguise Self",
    "Disintegrate",
    "Dispel Evil and Good",
    "Dispel Magic",
    "Divination",
    "Divine Favor",
    "Divine Word",
    "Dominate Beast",
    "Dominate Monster",
    "Dominate Person",
    "Dream",
    "Druidcraft",
    "Earthquake",
    "Eldritch Blast",
    "Enhance Ability",
    "Enlarge/Reduce",
    "Entangle",
    "Enthrall",
    "Etherealness",
    "Expeditious Retreat",
    "Eyebite",
    "Fabricate",
    "Faerie Fire",
    "Faithful Hound",
    "False Life",
    "Fear",
    "Feather Fall",
    "Feeblemind",
    "Find Familiar",
    "Find Steed",
    "Find Traps",
    "Find the Path",
    "Finger of Death",
    "Fire Bolt",
    "Fire Shield",
    "Fire Storm",
    "Fireball",
    "Flame Blade",
    "Flame Strike",
    "Flaming Sphere",
    "Flesh to Stone",
    "Floating Disk",
    "Fly",
    "Fog Cloud",
    "Forbiddance",
    "Forcecage",
    "Foresight",
    "Freedom of Movement",
    "Freezing Sphere",
    "Gaseous Form",
    "Gate",
    "Geas",
    "Gentle Repose",
    "Giant Insect",
    "Glibness",
    "Globe of Invulnerability",
    "Glyph of Warding",
    "Goodberry",
    "Grease",
    "Greater Invisibility",
    "Greater Restoration",
    "Guardian of Faith",
    "Guards and Wards",
    "Guidance",
    "Guiding Bolt",
    "Gust of Wind",
    "Hallow",
    "Hallucinatory Terrain",
    "Harm",
    "Haste",
    "Heal",
    "Healing Word",
    "Heat Metal",
    "Hellish Rebuke",
    "Heroes' Feast",
    "Heroism",
    "Hideous Laughter",
    "Hold Monster",
    "Hold Person",
    "Holy Aura",
    "Hunter's Mark",
    "Hypnotic Pattern",
    "Ice Storm",
    "Identify",
    "Illusory Script",
    "Imprisonment",
    "Incendiary Cloud",
    "Inflict Wounds",
    "Insect Plague",
    "Instant Summons",
    "Invisibility",
    "Irresistible Dance",
    "Jump",
    "Knock",
    "Legend Lore",
    "Lesser Restoration",
    "Levitate",
    "Light",
    "Lightning Bolt",
    "Locate Animals or Plants",
    "Locate Creature",
    "Locate Object",
    "Longstrider",
    "Mage Armor",
    "Mage Hand",
    "Magic Circle",
    "Magic Jar",
    "Magic Missile",
    "Magic Mouth",
    "Magic Weapon",
    "Magnificent Mansion",
    "Major Image",
    "Mass Cure Wounds",
    "Mass Heal",
    "Mass Healing Word",
    "Mass Suggestion",
    "Maze",
    "Meld into Stone",
    "Mending",
    "Message",
    "Meteor Swarm",
    "Mind Blank",
    "Minor Illusion",
    "Mirage Arcane",
    "Mirror Image",
    "Mislead",
    "Misty Step",
    "Modify Memory",
    "Moonbeam",
    "Move Earth",
    "Nondetection",
    "Pass without Trace",
    "Passwall",
    "Phantasmal Killer",
    "Phantom Steed",
    "Planar Ally",
    "Planar Binding",
    "Plane Shift",
    "Plant Growth",
    "Poison Spray",
    "Polymorph",
    "Power Word Kill",
    "Power Word Stun",
    "Prayer of Healing",
    "Prestidigitation",
    "Prismatic Spray",
    "Prismatic Wall",
    "Private Sanctum",
    "Produce Flame",
    "Programmed Illusion",
    "Project Image",
    "Protection from Energy",
    "Protection from Evil and Good",
    "Protection from Poison",
    "Purify Food and Drink",
    "Raise Dead",
    "Ray of Enfeeblement",
    "Ray of Frost",
    "Regenerate",
    "Reincarnate",
    "Remove Curse",
    "Resilient Sphere",
    "Resistance",
    "Resurrection",
    "Reverse Gravity",
    "Revivify",
    "Rope Trick",
    "Sacred Flame",
    "Sanctuary",
    "Scorching Ray",
    "Scrying",
    "Secret Chest",
    "See Invisibility",
    "Seeming",
    "Sending",
    "Sequester",
    "Shapechange",
    "Shatter",
    "Shield",
    "Shield of Faith",
    "Shillelagh",
    "Shocking Grasp",
    "Silence",
    "Silent Image",
    "Simulacrum",
    "Sleep",
    "Sleet Storm",
    "Slow",
    "Spare the Dying",
    "Speak with Animals",
    "Speak with Dead",
    "Speak with Plants",
    "Spider Climb",
    "Spike Growth",
    "Spirit Guardians",
    "Spiritual Weapon",
    "Stinking Cloud",
    "Stone Shape",
    "Stoneskin",
    "Storm of Vengeance",
    "Suggestion",
    "Sunbeam",
    "Sunburst",
    "Symbol",
    "Telekinesis",
    "Telepathic Bond",
    "Teleport",
    "Teleportation Circle",
    "Thaumaturgy",
    "Thunderwave",
    "Time Stop",
    "Tiny Hut",
    "Tongues",
    "Transport via Plants",
    "Tree Stride",
    "True Polymorph",
    "True Resurrection",
    "True Seeing",
    "True Strike",
    "Unseen Servant",
    "Vampiric Touch",
    "Vicious Mockery",
    "Wall of Fire",
    "Wall of Force",
    "Wall of Ice",
    "Wall of Stone",
    "Wall of Thorns",
    "Warding Bond",
    "Water Breathing",
    "Water Walk",
    "Web",
    "Weird",
    "Wind Walk",
    "Wind Wall",
    "Wish",
    "Word of Recall",
    "Zone of Truth",
]

const vars = () => {
    return {traits, ideals, bonds, flaws, maleFirstnames, femaleFirstnames, lastnames, spells};
}

// traits, ideals, bonds, flaws, maleFirstnames, femaleFirstnames,lastnames, characteristics, spells
exports.vars = vars;